### ISSUE TITLE
Compilation error doesn't say where the problem is

### ISSUE THREAD

**Issue by Asisayag** [openscore/score-language#71] opened 2015-01-31 07:41 UTC
Got a compilation error, but instead of pointing me to the problematic file, it pointed to 'reader'.
![image](https://cloud.githubusercontent.com/assets/7038610/5987341/f94f6fea-a92c-11e4-9b42-05dce70bb9a0.png)

**Comment by oritstone** [comment] 2015-02-02 07:46
@Asisayag , please attach the flow that caused the error

**Comment by Asisayag** [comment] 2015-02-03 21:16
Sorry, I don't have it. 
But, I got it in many compilation errors.

**Comment by meirwah** [comment] 2015-02-04 13:18
since we can not reproduce this.. i'm closing this..
reopen if you find a way to reproduce ...

**Closed by meirwah** 2015-02-04 13:18 UTC
