### ISSUE TITLE
How/Can you include python modules

### ISSUE THREAD

**Issue by okitac** [openscore/score-language#83] opened 2015-02-02 21:23 UTC
The following python action:
```yaml
      action:
        python_script: |
          import time
          print text
          time.sleep(10)
```
results in the following (non-intuitive) error message:
```
slang>run hello_world_sleep.sl
Command failed java.lang.RuntimeException: java.lang.RuntimeException: Reference: user.examples.hello_world_sleep.print_sleep in executable: hello_world_sleep, wasn't found in path
```
Is it possible to include python modules, and if not, why not?

**Comment by orius123** [comment] 2015-02-02 21:44
It is possible just the way you did works for me. Can you show th entire operation. It looks from the error like some import is not satisfied

**Comment by okitac** [comment] 2015-02-02 22:07
```
$ cat hello_world_sleep.sl
namespace: user.examples.hello_world_sleep

imports:
  ops: user.examples.hello_world_sleep

flow:
  name: hello_world_sleep
  workflow:
    sayHi:
      do:
        ops.print_sleep:
          - text: "'Hello, World'"
```
```
$ cat print_sleep.sl
namespace: user.examples.hello_world_sleep

operations:
  - print:
      inputs:
        - text
      action:
        python_script: | 
          import time
          print text
          time.sleep(10)
      results:
        - SUCCESS
```

**Comment by orius123** [comment] 2015-02-02 22:10
The operation name in the task should be print as in the operation name and not print_sleep like the operation file name. We are working on validating that the operation name is the same as the file.

**Comment by okitac** [comment] 2015-02-02 22:12
Ahhh, that's a major technical detail!  Can the error message get modified to make it obvious what the problem is, as well?  That's a variation I hadn't thought to chase down.

**Comment by okitac** [comment] 2015-02-02 22:17
Hm.  Along those lines, it seems to me like there's a setup for confusion in place there.  The definition for an operation is:

```
Operations file

    namespace
    imports
    operations
        operation(s)
            inputs
                required
                default
                override
            action
            outputs
                fromInputs
            results
```

which suggests that you could have multiple operations defined in a given operations file.  Given that, wouldn't you then need some way to define which one of the operations in a given file you actually want? (which would then make it problematic to have the operation name and the file name match, or at least having them match without adding a modifier, like <file_name>.<operation_name>, no?)

**Comment by okitac** [comment] 2015-02-02 22:20
Or, looking at the best practices, perhaps my question should be "does the definition for an operation need to be modified?"
```
    The namespace for a file is identical to the folder structure in which the file resides in the project.
    File names are all lowercase with words separated by an underscore (_).
    A flow or operation has the same name as the file it is in.
    Each file has one flow, one operation or a map of system variables.
    Flows and operations reside together in the same folders.
```

**Comment by orius123** [comment] 2015-02-02 22:21
This is due to a design issue we had, of enabling multiple operations within one file. Long story short... it complicates things. @oritstone just committed a change that force to have only one operation (or flow) in a file. We will release a new version of the cli with this fix soon.

**Comment by okitac** [comment] 2015-02-02 22:24
Great, thank you!
(and now that this yak's been shaved, time to try out what I wanted to do in the first place... )

**Comment by oritstone** [comment] 2015-02-03 08:06
@okitac, would you rephrase the error message above differently?
*...Reference: user.examples.hello_world_sleep.print_sleep in executable: hello_world_sleep, wasn't found in path*
It states that the reference *print_sleep* (the used operation name) in *hello_world_sleep* (the flow name) wasn't found in path. And indeed it wasn't found, because the name of the given operation was different.
Do you think that the error message should be written in a different way?

**Comment by okitac** [comment] 2015-02-03 11:45
Something closer to this perhaps? (the wording is awkward, but the idea is there, I hope?) It tells me what the reference it can't find is, where it is, what part of the flow I should be looking in, and how to fix the problem.

*No operation named user.examples.hello_world_sleep.print_sleep referred to on line 14 of flow hello_world_sleep found in imports path.  Operation name must be the same as the operation file name.*

**Comment by meirwah** [comment] 2015-02-04 13:25
this is duplicate with #59 right?

**Comment by orius123** [comment] 2015-02-05 21:06
yep. it's duplicate. closing

**Closed by orius123** 2015-02-05 21:06 UTC
Labels: duplicate

**Comment by oritstone** [comment] 2015-08-02 13:25
Duplicate of #59
